// Mocks generated by Mockito 5.4.6 from annotations
// in disciplina_visual/test/data/repositories/habit_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:disciplina_visual/data/datasources/local/database_helper.dart'
    as _i3;
import 'package:disciplina_visual/data/models/completion.dart' as _i6;
import 'package:disciplina_visual/data/models/habit.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  set setTestDatabase(_i2.Database? newDatabase) => super.noSuchMethod(
    Invocation.setter(#setTestDatabase, newDatabase),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> createTables(_i2.Database? db) =>
      (super.noSuchMethod(
            Invocation.method(#createTables, [db]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> createHabit(_i5.Habit? habit) =>
      (super.noSuchMethod(
            Invocation.method(#createHabit, [habit]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Habit>> getAllHabits() =>
      (super.noSuchMethod(
            Invocation.method(#getAllHabits, []),
            returnValue: _i4.Future<List<_i5.Habit>>.value(<_i5.Habit>[]),
          )
          as _i4.Future<List<_i5.Habit>>);

  @override
  _i4.Future<void> addCompletion(int? habitId, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#addCompletion, [habitId, date]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeCompletion(int? habitId, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#removeCompletion, [habitId, date]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Completion>> getCompletionsForHabit(int? habitId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletionsForHabit, [habitId]),
            returnValue: _i4.Future<List<_i6.Completion>>.value(
              <_i6.Completion>[],
            ),
          )
          as _i4.Future<List<_i6.Completion>>);

  @override
  _i4.Future<int> updateHabit(_i5.Habit? habit) =>
      (super.noSuchMethod(
            Invocation.method(#updateHabit, [habit]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteHabit(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHabit, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> deleteAllHabits() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllHabits, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFutureCompletions(DateTime? cutoffDate) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFutureCompletions, [cutoffDate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertSeedHabits() =>
      (super.noSuchMethod(
            Invocation.method(#insertSeedHabits, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
